import categories from '../categories/data';

const description = `

### Thin and light design, thin 5.9mm, soft rounded edges, elegant silver color

Apple iPad Pro 11 "(2020) Wifi 128Gb (Silver has the same design as its predecessor, but there are changes such as the rear camera system is placed in a square and weight 471g for a feeling of weight. Size 247.6 x 178.5 mm and a thickness of only 5.9mm, iPad Pro 11 2020 will be extremely thin and light, convenient to carry and use on the go.

Soft rounded edges provide a comfortable, solid hand feel, creating harmony in design. iPad Pro 11 2020 comes in elegant and classy silver.

### 120Hz screen, 16 million colors, 11-inch IPS LCD panel

Using a screen with a frequency of 120Hz will give iPad Pro the ability to display sharp images, fast image processing speed. In addition, the 120Hz frequency screen for Apple also symbolizes touch sensitivity, helping to scan finger movements and respond quickly. As a result, users will have a better experience, fast and responsive operations, avoiding image glitches and delay.

Apple also equips the iPad Pro 11 2020 with an IPS LCD panel of 16 million colors, with a resolution of 1668x2388 pixels on an 11-inch screen size to help display sharp, vivid colors, high contrast. In addition, the screen technologies like ProMotion, True Tone give users authentic and wonderful experiences. In addition, the iPad Pro 11 2020's screen is also covered with an oleophobic coating that helps prevent fingerprints and glare effectively when used outdoors.

### Perfect Experience

Everything you experience on iPad (2019) 10.2 "Wifi + Cellular 32GB MW6D2ZA / A (Gold) has great picture and sound, thanks to the 10.2 inch Retina display and stereo system. Apple TV, you'll have access to popular streaming services and enjoy blockbuster TV shows and movies.

### Impressive performance when owning the A12Z Bionic chip

In addition to the design and screen, Apple also equips the iPad Pro 11 2020 with strong and outstanding performance when owning an 8-core A12Z Bionic chip with an architecture that brings high efficiency in heat dissipation. In addition, the new controller system is improved, optimized to bring higher performance to the iPad Pro 11 2020. Thanks to these improvements, the iPad Pro 11 2020 will be able to edit 4K video, design smooth 3D image, meeting all usage needs.

The 128GB internal memory allows you to comfortably use the memory to store pictures, videos, songs, applications, ... In addition to the 128GB standard memory version, iPad Pro 11 2020 version with higher memory capacity That's the 256GB iPad Pro 11 2020.

### Improved rear camera system with LiDAR depth gauge

Unlike previous iPad Pro brothers, in the iPad Pro 11 2020, the camera system has been greatly improved with the 2 rear camera system with a LiDAR depth gauge so you can capture every moment professionally. With a 12MP main camera and 10MP ultra wide-angle camera, the LiDAR scanner senses depth with a measuring distance of up to 5m around the subject, outdoors and indoors. Thanks to the new camera system, you can record every image, edit and edit videos in stunning 4K resolution.

In addition, the iPad Pro 11 2020 is also equipped with a 7MP selfie camera that supports 1080p video so you can video call high quality, take beautiful selfies or even use the iPad as a camera to record vlogs. quality to share with friends.

`;

const products = [
  {
    id: 1,
    name: 'Avatar: The Way of Water',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 20000,
    discount: 10,
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/avatar.jpeg'],
    tag: 'New',
    merchant: 'Kelvin Stores',
    stock: 10,
    sold: 3,
    tags: ['Trending', 'Cheap', 'Hot'],
    slug: 'avatar-the-way-of-water',
  },
  {
    id: 57,
    name: 'Apple macbook pro 14 M1',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 390,
    brandName: 'Apple',
    amount: 8000000,
    discount: 0,
    tag: 'New',
    merchant: 'Apple Stores',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/macbook.jpeg'],
    slug: 'apple-macbook-pro-14-m1',
  },
  {
    id: 59,
    name: 'Asus ROG Strix G15',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['white', '#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 394,
    brandName: 'Asus',
    amount: 5000000,
    discount: 12,
    tag: 'New',
    merchant: 'Asus Stores',
    stock: 17,
    sold: 3,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/asus.jpeg'],
    slug: 'asus-rog-strix-g15-1',
  },
  {
    id: 62,
    name: 'Ant man: Quantumania',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 0,
    sold: 150,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://publicpayfiimages.s3.amazonaws.com/banner/antman_image.jpeg',
    ],
    slug: 'ant-man-quantumania-1',
  },
  {
    id: 64,
    name: 'Hot Jollof rice',
    categoryId: 55,
    categoryName: 'Luxury Food',
    rate: 3,
    totalRates: 78,
    description,
    specifications: [
      { key: 'Type', value: 'Domestic dishes' },
      { key: 'Protein', value: 'Chilli Beef, Chicken, Turkey, Fish' },
    ],
    subCategoryId: 60,
    subCategoryName: 'Fast Food',
    brandId: 62,
    brandName: 'Bukka Hut',
    amount: 3000,
    discount: 10,
    tag: '',
    merchant: 'Bukka Hut',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/jollof.jpeg'],
    slug: 'hot-jollof-rice-1',
  },
  {
    id: 65,
    name: 'Toy Story 4',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2960,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/toystory.jpeg'],
    slug: 'toy-story-4',
  },
  {
    id: 66,
    name: 'Croods 2',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    colors: ['white', '#FFF0EB', 'black', '#FFE923'],
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 7,
    brandName: 'Star Wars',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/croods2.jpeg'],
    slug: 'croods-2',
  },
  {
    id: 1,
    name: 'Avatar: The Way of Water',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 20000,
    discount: 10,
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/avatar.jpeg'],
    tag: 'New',
    merchant: 'Kelvin Stores',
    stock: 10,
    sold: 3,
    tags: ['Trending', 'Cheap', 'Hot'],
    slug: 'avatar:-the-way-of-water',
  },
  {
    id: 57,
    name: 'Apple macbook pro 14 M1',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['white', '#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 390,
    brandName: 'Apple',
    amount: 8000000,
    discount: 0,
    tag: 'New',
    merchant: 'Apple Stores',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/macbook.jpeg'],
    slug: 'apple-macbook-pro-14-m1',
  },
  {
    id: 59,
    name: 'Asus ROG Strix G15',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['white', '#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 394,
    brandName: 'Asus',
    amount: 5000000,
    discount: 12,
    tag: 'New',
    merchant: 'Asus Stores',
    stock: 17,
    sold: 3,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/asus.jpeg'],
    slug: 'asus-rog-strix-g15-2',
  },
  {
    id: 62,
    name: 'Ant man: Quantumania',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 0,
    sold: 150,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://publicpayfiimages.s3.amazonaws.com/banner/antman_image.jpeg',
    ],
    slug: 'ant-man-quantumania-2',
  },
  {
    id: 64,
    name: 'Hot Jollof rice',
    categoryId: 55,
    categoryName: 'Luxury Food',
    rate: 3,
    totalRates: 78,
    description,
    specifications: [
      { key: 'Type', value: 'Domestic dishes' },
      { key: 'Protein', value: 'Chilli Beef, Chicken, Turkey, Fish' },
    ],
    subCategoryId: 60,
    subCategoryName: 'Fast Food',
    brandId: 62,
    brandName: 'Bukka Hut',
    amount: 3000,
    discount: 10,
    tag: '',
    merchant: 'Bukka Hut',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/jollof.jpeg'],
    slug: 'hot-jollof-rice-2',
  },
  {
    id: 65,
    name: 'Toy Story 4',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2960,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/toystory.jpeg'],
    slug: 'toy-story-4--3',
  },
  {
    id: 66,
    name: 'Croods 2',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 7,
    brandName: 'Star Wars',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/croods2.jpeg'],
    slug: 'croods-2',
  },
  {
    id: 67,
    name: 'The Lion King',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2000,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/lionking.jpeg'],
    slug: 'the-lion-king',
  },
  {
    id: 67,
    name: 'The Lion King',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2000,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/lionking.jpeg'],
    slug: 'the-lion-king',
  },
  {
    id: 1,
    name: 'Avatar: The Way of Water',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 20000,
    discount: 10,
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/avatar.jpeg'],
    tag: 'New',
    merchant: 'Kelvin Stores',
    stock: 10,
    sold: 3,
    tags: ['Trending', 'Cheap', 'Hot'],
    slug: 'avatar:-the-way-of-water',
  },
  {
    id: 57,
    name: 'Apple macbook pro 14 M1',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['white', '#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 390,
    brandName: 'Apple',
    amount: 8000000,
    discount: 0,
    tag: 'New',
    merchant: 'Apple Stores',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/macbook.jpeg'],
    slug: 'apple-macbook-pro-14-m1',
  },
  {
    id: 59,
    name: 'Sony Head phones',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['white', '#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 3,
    subCategoryName: 'Headphones',
    brandId: 2,
    brandName: 'Sony',
    amount: 500000,
    discount: 12,
    tag: 'New',
    merchant: 'Sony Stores',
    stock: 17,
    sold: 30,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/T/P/206219_1669150232.jpg',
    ],
    promoEndTime: Date.now() + 259201474, // now plus 3 days
    slug: 'sony-head-phones',
  },
  {
    id: 62,
    name: 'Ant man: Quantumania',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 0,
    sold: 150,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://publicpayfiimages.s3.amazonaws.com/banner/antman_image.jpeg',
    ],
    slug: 'ant-man-quantumania-3',
  },
  {
    id: 64,
    name: 'Hot Jollof rice',
    categoryId: 55,
    categoryName: 'Luxury Food',
    rate: 3,
    totalRates: 78,
    description,
    specifications: [
      { key: 'Type', value: 'Domestic dishes' },
      { key: 'Protein', value: 'Chilli Beef, Chicken, Turkey, Fish' },
    ],
    subCategoryId: 60,
    subCategoryName: 'Fast Food',
    brandId: 62,
    brandName: 'Bukka Hut',
    amount: 3000,
    discount: 10,
    tag: '',
    merchant: 'Bukka Hut',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/jollof.jpeg'],
    slug: 'hot-jollof-rice-3',
  },
  {
    id: 65,
    name: 'Toy Story 4',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2960,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/toystory.jpeg'],
    slug: 'toy-story-4--2',
  },
  {
    id: 1,
    name: 'Avatar: The Way of Water',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 20000,
    discount: 10,
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/avatar.jpeg'],
    tag: 'New',
    merchant: 'Kelvin Stores',
    stock: 10,
    sold: 3,
    tags: ['Trending', 'Cheap', 'Hot'],
    slug: 'avatar:-the-way-of-water',
  },
  {
    id: 57,
    name: 'Apple macbook pro 14 M1',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['#1355FF', '#FFF0EB', 'black', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 390,
    brandName: 'Apple',
    amount: 8000000,
    discount: 0,
    tag: 'New',
    merchant: 'Apple Stores',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/macbook.jpeg'],
    slug: 'apple-macbook-pro-14-m1',
  },
  {
    id: 59,
    name: 'Asus ROG Strix G15',
    categoryId: 26,
    categoryName: 'Technology',
    colors: ['#FF5A1F', '#E3D3EF', '#FF8154', '#FFF0EB', '#061A95', '#FFE923'],
    rate: 3.4,
    totalRates: 567,
    description,
    specifications: [
      { key: 'Screen', value: 'LED Retina Display, 14inch' },
      { key: 'Chip/CPU', value: 'Intel Core 19' },
      { key: 'RAM', value: '64Gb' },
      { key: 'Operating System', value: 'Linus OS' },
    ],
    subCategoryId: 39,
    subCategoryName: 'Laptops',
    brandId: 394,
    brandName: 'Asus',
    amount: 5000000,
    discount: 12,
    tag: 'New',
    merchant: 'Asus Stores',
    stock: 190,
    sold: 200,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/asus.jpeg'],
    promoEndTime: Date.now() + 259291474,
    slug: 'asus-rog-strix-g15',
  },
  {
    id: 62,
    name: 'Ant man: Quantumania',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 123,
    brandName: 'Marvel',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 0,
    sold: 150,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://publicpayfiimages.s3.amazonaws.com/banner/antman_image.jpeg',
    ],
    slug: 'ant-man-quantumania',
  },
  {
    id: 64,
    name: 'Hot Jollof rice',
    categoryId: 55,
    categoryName: 'Luxury Food',
    rate: 3,
    totalRates: 78,
    description,
    specifications: [
      { key: 'Type', value: 'Domestic dishes' },
      { key: 'Protein', value: 'Chilli Beef, Chicken, Turkey, Fish' },
    ],
    subCategoryId: 60,
    subCategoryName: 'Fast Food',
    brandId: 62,
    brandName: 'Bukka Hut',
    amount: 3000,
    discount: 10,
    tag: '',
    merchant: 'Bukka Hut',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/jollof.jpeg'],
    slug: 'hot-jollof-rice-4',
  },
  {
    id: 65,
    name: 'Toy Story 4',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2960,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/toystory.jpeg'],
    slug: 'toy-story-4--4',
  },
  {
    id: 66,
    name: 'Croods 2',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 7,
    brandName: 'Star Wars',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/croods2.jpeg'],
    slug: 'croods-2',
  },
  {
    id: 67,
    name: 'The Lion King',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2000,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/lionking.jpeg'],
    slug: 'the-lion-king',
  },
  {
    id: 66,
    name: 'Croods 2',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 7,
    brandName: 'Star Wars',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/croods2.jpeg'],
    slug: 'croods-2',
  },
  {
    id: 67,
    name: 'The Lion King',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2000,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/lionking.jpeg'],
    slug: 'the-lion-king',
  },
  {
    id: 68,
    name: 'The Adam Project',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 13,
    subCategoryName: 'Comedy',
    brandId: 133,
    brandName: 'Pixar',
    amount: 2000,
    discount: 6,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://publicpayfiimages.s3.amazonaws.com/banner/adamproject.png',
    ],
    slug: 'the-adam-project',
  },
  {
    id: 69,
    name: 'Guardians of the Galaxy Vol. 3',
    categoryId: 1,
    categoryName: 'Movies',
    rate: 4.5,
    totalRates: 588,
    description,
    specifications: [
      { key: 'Quality', value: '3D 4K' },
      {
        key: 'Cast',
        value:
					'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Cliff Curtis',
      },
      { key: 'Subtitles', value: 'English, French, Spanish' },
      { key: 'Audio', value: 'English [Original], French' },
      { key: 'Director', value: 'James Cameron' },
      { key: 'Box Office', value: '$2,790,439,000' },
      {
        key: 'Production',
        value:
					'Lightstorm Entertainment, Dune Entertainment, Ingenious Film Partners',
      },
    ],
    subCategoryId: 12,
    subCategoryName: 'Action',
    brandId: 124,
    brandName: 'DC',
    amount: 2000,
    discount: 0,
    tag: '',
    merchant: 'Ocinemas',
    stock: 100,
    sold: 35,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: ['https://publicpayfiimages.s3.amazonaws.com/banner/guardian.webp'],
    slug: 'guardians-of-the-galaxy-vol.-3',
  },
  {
    id: 64,
    name: 'Large Beef Pizza',
    categoryId: 55,
    categoryName: 'Luxury Food',
    rate: 3,
    totalRates: 78,
    description,
    specifications: [
      { key: 'Type', value: 'International dishes' },
      { key: 'Protein', value: 'Beef, Chicken, Turkey, Fish' },
    ],
    subCategoryId: 56,
    subCategoryName: 'Bakery',
    brandId: 59,
    brandName: 'Burger Kings',
    amount: 9000,
    discount: 2,
    tag: '',
    merchant: 'Burger Kings',
    stock: 0,
    sold: 150,
    tags: ['Trending', 'Cheap', 'Hot'],
    images: [
      'https://publicpayfiimages.s3.amazonaws.com/banner/beef_pizza.jpeg',
    ],
    slug: 'large-beef-pizza',
  },
];

export const featuredMovies = [
  {
    id: 1,
    title: 'The Adam Project',
    date: 'March, 2022',
    images: 'https://publicpayfiimages.s3.amazonaws.com/banner/adamproject.png',
  },
  {
    id: 2,
    title: 'Avatar: The Way of Water',
    date: 'December, 2022',
    images: 'https://publicpayfiimages.s3.amazonaws.com/banner/avatar.jpeg',
  },
  {
    id: 3,
    title: 'Ant man: Quantumania',
    date: 'February, 2023',
    images: 'https://publicpayfiimages.s3.amazonaws.com/banner/antman_image.jpeg',
  },
  {
    id: 4,
    title: 'Guardians of the Galaxy Vol. 3',
    date: 'May, 2023',
    images: 'https://publicpayfiimages.s3.amazonaws.com/banner/guardian.webp',
  },
  {
    id: 5,
    title: 'Toy story 4',
    date: 'July, 2023',
    images: 'https://publicpayfiimages.s3.amazonaws.com/banner/toystory.jpeg',
  },
  {
    id: 6,
    title: 'Croods 2',
    date: 'September, 2023',
    images: 'https://publicpayfiimages.s3.amazonaws.com/banner/croods2.jpeg',
  },
];

const getProductsByCategory = (categoryName: string) => {
  const result = products.filter((item: any) => item?.categoryName?.toLowerCase?.()
    === categoryName?.toLowerCase?.());
  return result;
};

export const getCategoryProducts = () => {
  // top 4 categories
  const categoryProducts = categories?.map((category) => ({
    category: category?.name,
    products: getProductsByCategory(category?.name),
    subCategories: category?.subCategories,
  }));
  return categoryProducts;
};

export const getRandomProducts = (count: number) => {
  const result = [];
  for (let i = 0; i < count; i += 1) {
    const randomIndex = Math.floor(Math.random() * products.length);
    result.push(products[randomIndex]);
  }
  return result;
};

export default products;
